from skfuzzy import control as ctrl


def get_rules(densidade, velocidade, espera, incidentes, tempo_verde):

    [# Densidade Baixa
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['baixa'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['baixa'] & incidentes['media'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['baixa'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['media'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['media'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['baixa'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['baixa'] & incidentes['baixa'], tempo_verde['longo']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['baixa'] & incidentes['media'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['baixa'] & incidentes['alta'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['media'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['media'] & incidentes['media'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['media'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['baixa'] & incidentes['baixa'], tempo_verde['longo']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['baixa'] & incidentes['media'], tempo_verde['longo']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['baixa'] & incidentes['alta'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['media'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['media'] & incidentes['media'], tempo_verde['medio']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['baixa'] & velocidade['alta'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),

    # Densidade Média
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['baixa'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['baixa'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['baixa'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['media'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['media'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['baixa'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['baixa'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['baixa'] & incidentes['media'], tempo_verde['medio']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['baixa'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['media'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['media'] & incidentes['media'], tempo_verde['medio']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['media'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['baixa'] & incidentes['baixa'], tempo_verde['longo']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['baixa'] & incidentes['media'], tempo_verde['medio']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['baixa'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['media'] & incidentes['baixa'], tempo_verde['medio']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['media'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['media'] & velocidade['alta'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),

    # Densidade Alta
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['baixa'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['baixa'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['baixa'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['media'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['media'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['baixa'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['baixa'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['baixa'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['baixa'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['media'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['media'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['media'] & espera['alta'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['baixa'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['baixa'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['baixa'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['media'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['media'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['media'] & incidentes['alta'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['alta'] & incidentes['baixa'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['alta'] & incidentes['media'], tempo_verde['curto']),
    ctrl.Rule(densidade['alta'] & velocidade['alta'] & espera['alta'] & incidentes['alta'], tempo_verde['curto'])]
    return rules
